(function () {
  "use strict";

  // LightParkour hero: one motion seed grows into a skill family.
  //
  // The figure follows the recovered Motion 02 trajectory in side view at
  // 25 fps. Each frame's silhouette was traced off the skinned mesh
  // offline and stored here as polygon outlines in centimetres, so the page
  // gets true anatomy without shipping a WebGL runtime or a 1.4 MB GLB.
  //
  // The sequence is editorial rather than literal: one recovered trajectory
  // enters as the seed, physics resolves its contact, then the path unfolds
  // into an ordered family spanning four terrain scales. The family is always
  // faintly present as potential and is revealed branch by branch. Honors
  // prefers-reduced-motion with the fully grown tableau.

  var VERSION = "14.3.0";
  var VIEW_W = 1600;
  var VIEW_H = 760;
  var MAX_DPR = 1.5;
  var MAX_PIXEL_AREA = 6500000;

  var INK = [26, 32, 30];
  var SAGE = [78, 101, 91];
  var CONTACT = [142, 103, 88];
  var PAPER = [243, 242, 238];

  var GROUND_Y = 636;
  var SCALE = 1.18;        // logical units per centimetre
  var X0 = 890;            // logical x of the clip origin
  var DATA_FPS = 25;

  // Traced silhouettes: zig-zag varints in base64, half-centimetre units.
  var PACKED = "qGC2EXgYQCOFIHINARGHFRALDDRADHAXahBKVA3BFRAZGXATFTCFAtCBBATDDANLvBBbLdF1DGTONsBTADRADBlCCDECmBBEAYDCBkBFSAmBMuBAqBDEAyBBCA2BJUBgBGUSiBCWFFDIBLFGDFFGAQEMDYAMEODQAiBUoBAWLWAWQUHoOCiFVgYOCIDUPGLAJDDKLFHDVRAHNARMLYrBAzBFRCLBBAVCBAxBBDCxCBDAVDDBfFRDfNpBAtBBDArBDHEDAXQRsBTADLBrBADCfBJKCMAsBBCAWDCAOFWAiBMqBAqCBCAkCLqBAgBUqBEcDAALFCAKDLJEAOGMAMFSCeDOAeOYIWBWLYAKGQIIJmOC6EX+XcAGBMNGLAPGJHdDDPAHJATYfKVAxBFNAPGHJAANEDA3BDHEDAfCBBjCDDARFTFxBLdBpCBBAxBCHQRgBNKAEDDDRADDxCEHGAMEEA+BDCB2BBGCCCeKYCmBBCAwBDCA+BJkBAeW0BBMDAAHFMGaHUAaHcAUa0BAMLYDSGOMMLmOCiER+XWAMDKLGLATGFJfRBHJALDBEJIHWrBD3BFRKHCLLGAdEDAVDDEjEDDHxCPrBArBBDAZBBAdCDAJKNQJkBLDDPANFfAVGbAHEEkBCCFwDS4BF0ELgBAaa8BBICeHODYHYAmBSaIUBWJOAYMQNkOC+EF+XSBQNGLATKLJLBNFDHCFBHHBLAHILWrBD1BFXMJGLDBJIALCFFDB9BGVA1CDDAVBDAXDBAXNlBAfDDAfBBA1BCHSNWLSBCFDDfAFFLADEHDVGNABEXADEAOGSDuDECCYOkBF2EHUBgBCEAMUmBGYBgBR6BAeGOOSKSAOLYAYMQPiOE6EL6XWCIBQRGNBLILFFBTFDPALTANGFWrBDxBHXYfFBHICVFABOBPBDDrBEBCjBEBAzCDBAdBBAfPnBB3BDBAZBDAlBCHMLuBTCDvBBFHFCbAfKRADEASGMAUECAgDU0BD4DBEAeHUDaEEAOUmBGWAgBP0BBiBGUSUISASLUASIOIIUnBgEEAAPCDApBEBDVNUAQCETiOEuFC6XQAURGNDNKPFBDTHFNAHFBJARILQlBDnBHhBSTIRDAFIBTDADSBXDAAQDAArBBDCBAPGPAREDA3CDBAtBHfFHAPDBAdBBAZDDBpBGTKJmBNIHPBDBtBCABGBFHDETAZIbEFEASIaEiDaiCD+BBEA4BBCAWJUASBCCEASYsBCYECDkBLoBAqBiByBAOLYCYQQSpBsEGACxBEBAlBDPTWAgBCCVgOEiFD4XUCULKTATGFFJBPHHLCJJFRY3BAVDDBdFLAHajBAFHEBTDCAODABVDCAUBPFFAhBCBGvBEBAjDDDAlBNlBFrCDDArBOPeNSDADFDrBAJCBBPAGFBDRAjBMfGBUKUAOCEG8Ca4BBsCBCA2BDCAQHUAmBWsBGWAiBBEAOJkBAeGQeoBAQLcEQMSWnBqFEAAlBCDAVEDA5BDPbcCmBS4BX+NE2ED0XaCIBONGLATEJDHDRDDRANVALGFQpBAVFPANJVenBELJCBPDABKANFDBMHHAKBPDBARKZChBEBAjER1BDzBFVAhBEJKJeNSDADDD1CAIHBDFABCRAlBQLANMKSGYI8CQiBOYFqELkBAgBEMUkBIiBLiDGYceGMAQJQAaOQgBhB+FEAAFFTATCDATEBBlDdYJSAOMkBAKOmBESZ+NC2FK0XQAUNGLAXGFAFFFBPFFRALRAPSrBAZFLALJZejBETJGATFABKAPFBAcDAAZFCAWBPFLALSlCAfCDBrCCLRxBATBDAXDBF7BEBALKJwBTAF1CAHKECAYCEF2DKWBIVjBJhBPrBDZBBIViBdIBBDNADCBBjBOZGHKOkBQoDe0BFuELiBAcMcKSKeAqBFWA0BIUegBAUHQAYQSb8NC8FIyXQCIDSNITDLGNFJBNDDPCJJHRSzBAXFLJlBkBpBAHBLJFAHHBBFDCCCBKDLFCEGBIHHASBAAZDFS7BErBCBAjDHRJjBAXBBARFTArBUTgBLGHhBDBExBADEC8CBCDsBEEAQMeBKBFdpBhBhDATGLmBhBBFFAlCYHEBKQoBGqBECASIkBewBFwELiBAYKYOYMoBD0BBCAwBMaUSKOASJSAUQUd6NCoGIuXWCIBMLKTBNILHLDNFFLENNFLALGHKfAZFJJlBQTWXELFAALVVDCCCBWARHDHGBsBDAA9BKTIjBElBCBEhDRtBDpBBDAPFVAhBUTqBPDDPABDTADEpBDFIAUCEB8DOsBBYJdTXLXHZRjBJdANGLmBhBAFJAXGZQTGHGAGWsBQ6CQaSUCMBIAkBDEB6CJSBkBGUUgBIeA4BBEAsBCMKQgBiBEKLYASCKMKhB6NCmGKsXaCQLMTDRKLJJBPHDLCLLFLALMlBAZJRFdMRaZGJAHFNDALNHFFGFBHGEQFOASFCALCBBvBGHOxBEjBCBEzCCBBTPhBF5BBBAPFTAXCHIHULeHCFPADDZABEnBDFICmBEEAmBDCAmBBKCCAYQmBAQHQDfhBnBfjCNpBGXmBlBHDrCgBDKYyBQwCoB4BD4BBED0CHSDeGYWgBKoBAuBBCC2BMWiBiBCKLYAQMQjB4NC6GOoXYCULIRALBDINHLDNFFDENDPXMpBAfPjBGPMRURKLCLFBAFJJFCNNDACEBSAPHDAMHHESFMASFGD3BKROxBEdCBAdEBAjBCDAfRrBBlBJjBAtBSNoBNCFHDFEBDfADEjBDFKCeEEDwDGWMcBQHSDHDflBvBrB9CATGLgBjBBDFAbMdSLCHKWmBagDOWYcBgCDCA2BBCAYFKDcBECCEYYqBIaAOCEAaBEC4BKUmBmBCMJaAMIQKKlB2NCgHQmXaCIDIFMRAPDBKPJJDRXBPVALKdAhBPhBAFQZiBlBARPLAKHNPHBGFDHIECAMFMASFMDAAvBBHMXOvBAJGRAXEDCzBEDAPRpBDjBBBAPJhBAjBSPoBNCFHDFEBDfADEjBDFKCEAUEEA4CDCAMEECcMcASFQHMDRATHTddf9BFFNjBAPELWbMHHDdMNMZMHKSaIUYwCOYceDiCBEA0BDEAUHWAiBe4BIeAgCCEAYGSsBsBEOHODSGQOMnB2NCqGUiXYCKBIJKPAXGHHLDNFDDCNBTbGLAREDAhBPdALSdgBfEXNJHERPRGCOFOASFMFCAtBBDa/BCXGNErBCDATEDAhBRrBFxBJjBAZSToBNCFDDJEBDfADEjBDDEAcECAYCCBgDSuBAMRoBFbATFPjBhBTnBLNXxBAHKVafBDFA/BkBHGAKYmBe2CKQeeBsCDEA0BBEAOJWAgBe4BIaEMA0BCEEkBIQmBiBGSHOAaQUpB0NCwGWgXaCIDOLGLAXGLFBHVXDRXCbEBApBPZALKRMRgBfCTJJRANLRCDECEAOBEDaJMCLBrBOZMhBGhBCDANEDG5BCDATRnBFvBHfDjBEHKLeNOBCFDDJEBDfADEjBDDEAYGWAmCBCAWCCEaOiBFUPeJ9BpBpBHRdnBRjBAXMTUXADFAPGnBeJCFIAIOSSkBYgCKSiBgBFoELkBAcIYWgBKiBE6BCCAWGUWcKESSEMJSAYOQrByNC6Fc+WWAKBMNGLAXGJFDFTDDHCLBTVEpCRhBarBkBhBAPNLRCRNPGASFMASHOBADzBMRAFOdAHMjBKjCGPDVLTFTFvBHdAnBKLeNSBAFFDpBABEjBDHIAOGWAwDSsBAOVwBDJFxBFNpBlBxBpCHVCVSdMLHDFGBDFEfaRIHIAKYcmB6CsBsBFqELkBAaGSSaSqBCcEEAgBMwBQSSKQQCMHQAWOSvBwNC0GgB6WWCMFKJGLAXGLFBDPFJXBTVELA3BPXBLarBkBfCRLNFEFDHEEMLOAHGLDLNJTGEOFMASLYDzBc5BAJMfK9BGNAZRlBJ7BHdAfQPqBNAFPDbADElBDHIEeCCAmBEEDgCEECWOeAKb2BLrCvBrBrB5BNbDHERMXOPBFHAJEBGHCPQZQDMcmBoByCQUeYBKAaDCBkDJWBiBMeUgBMiBCcEEAYCCAOGWGMWWQGMMEMJSAUMQxBwNC2GmB4WQAIBQNGLAVGLHLDPVAFDRVAfCDBfRdADatBmBhBARLJFCJBDEGCAGNSFQNMBFEFMLGLCVNLPGDDCUFOAQNWArBDFgB9BMlBK3BIZANNdFTDdN7BAZQPqBNAFPABDVABEpBDJKEYCEAUECAgDU0Bf8BFVFxBFLNLLFbbhBrBVhBEfOZKHBFJAxBmBLOAKYasB2CWYcWDmBBEDgDLkBEeMYMOOgBIgBG2BKaYcWKKKCMHQAWQSzBuNC+GuB0WQBULIXBDAJGLFDHVTAZVBFCLBxBVhBevBmBjBENNNRADEGEAGHIFQZcBFKPOREdLHTEDEGEFQASPcBpBBDWlBMZQvBIzBGLAZLVHbFpBLvBAPORWJQDGHPABDRADEfAFDLEAcGWAgDGWOeAKhB+BP1CTTHBVTxB5BRdCZQdIHFFXQfcLMAIYYMSmBmCaaYQBsBDCB+CJWAOBECWMYMOSoBIgBAOEEAOGYMaQQUKQMEMJQAUGMKK1BsNC4GmBuWcCQJIPELDBALGLFBFVDDNELFTTAxBBBALVjBevBqBlBANNJNADEEGNSBIZaBDGPMLGLELDJJHLAJEDGGBAIFOASLaDxBMNWvBGVGJM5BKXDXRlBH3BJZBdCHIHwBTAF1CADEAYGSAoBCEAaBCCkBUyBhBiCDANvCFLJJXLVVlBpBXfBLCROfKHJBLGzB2BgBkBkB+BSWsBiBDuBBEA6BDEAcHWAmBIUSYSmBIgBAQQyBSYsBaCIHSAUGM3BsNCwGsBsWSAQFKJIVBDALGHRbTAbZAxBHXPPAJcpBQPMFQRAPHFTDDGECNUAGdgBBHGLSXCLBPJFLALGAGGCFMASPeDtBSVUpBQpBIrBKTAZRjBL/BJbAhBIHeNSDAH1CADEAUGSAeCCAqCKeKUAKlBkCFJANBDFtBFVPPTHrCrCNXATUrBBDFA7B6BAIgBgBwBqCSUiBSB2BDCA+BBEAWJWAiBKWSWUuBSsCMYWWYIMKEKJSAUUW7BqNE8GyBoWMCKDSLGLAZGLFDHVFBNCNHPPDFEDALDBBlBVZBJerBsBlBCLJNTBDIEBAENYhBiBBHGNMLGLEZJHJCBBLGBDMRSpBMtBGLAJITANTvBJxBHXDrBONqBNEDHDxCADEAUCEEiBCEAsCKgBOcAGRWbyBJ9BDBARHXPLRFLJ1BxBZhBDHEXMdEFADJAVUHOXYBIgBe0BsCWUgBQD8BBCA8BDCAUHWAgBMaSYUsBIeAMSuBWaeMOKCIHQAWQUQVmOEAOdAVGNDCDFRY9BoNE6GyBiWWCIBONGLAZGJRbTAXNFJDvBHTRTAJIHSdyBrBAJLLRAAKJMDIjBiBALGLMLKdNNHEDDLKADKPWrBIhBKVAHIRAZTrBJxBHXDpBMJQHgBLDDLADBZABCnBBFGASIkBAuBEEDUEEASGUOaAKvBqCHzBFPARFRNNfNRPhC9BFLAXKZIPHDXWFMTWFIAIcYyBkCWWoBUBgCDEA6BBEAQFKAMBCAaOiBIIcyBKwBQmBWcUMQCQOJUAUOUSXiOCAQdANERDCBFTYEG/BoNEyG2BgWOCaNINAVBBGPFFDNHHFEPDZRH7BFLRPDJKHSdWVGAWTCLJLTDAMJKDKnBkBBDKXSTCTFLDEFFLGDDavBW5BAJKZBXTrBALVrCATQRsBPDDPABBLADCzBADEAQIiBAeEEA6BW8BHIpBiCFDARLxBANHXNJJDbNzBrBfhBBLCTKdGFBDFAZWfuBEIMGmBkBuB6BKKmBQDmCBEA4BLoBAYIYYgBYwBEQQyBWgBSMYGQMHSAYQUQX8NCAMXALGPDLVcCEhCmNEwG0B6VaCKFMLGJDXGPFBHVVAfVAPBBANFXFLXXalBWVQFSVBHHHNFFCBGCCJMDInBiBBFGPQNGfNHLABCBDgB5BQxBKXAZNXFRL3BHXDhBONqBNEFDD1CADIGoBCEAaEEA6BIgBOcAITYhB0BJ5BDDBfFRTPNBRJjCzBVZBFAVIhBGHFBXUNaRUAGKKMG0C6CQMWEKIFUDuDJmBCeIUQSe2BOyBSiBWWSKSCQOFGFYGQKMMb8NEAOfEXFHRajCkNEmG8B2VWAUPGLBXELDDFTFDPCbNJJBdJdXVBJkBrBMNMBWVBHJLPBDECGNSpBkBAPGLQNALGLDHLDLCBDOVQbS1BOfDXDFPfALTlCDdMNcNSBCFHDnBADEjBDFIAOGQCmBECCqCY2BTWnB6BTtDPPZJdR7BrBPPBHAfGXGJHAXYLYPSAIWOwCyCYQeKFWBwDHWAODEGgBsBmCQgBEYSkBWYYMMAUOJYEUKOMd8NCAAFQZAbVSlCkNCwG6BwVWCIBSPEPBTGLFBJXTAXJNNARHdFLbbyB3BSDSTBHJLPBDEAGVafaDDIVONGTAFFHJBFCDHetBYhCINAXTlBJrBNrBDZEJMJsBPDDPABDjCEDEAOGQCgBECCuCGUSeAIRSdsBPQDjBLvBARFNJJLFRDRHzBjBlBdFPATGRALGHFBVWJWRWAMaOSOgCiCkBQQCDYBCBwDJWAmBEIyBwCOqBe0BSQWKMASMHWAOEKOQpCiNE+F6BqVcCQJINELDRGHPbRCbNJLFbJXZZDJWZcbMAOLIHAHHJRFDEAGVWlBeBDIXQLGTAJDDVDgBxBGVc/BBTTlBFhBRzBDZUTeLIACDDD1CADGAMIeASECG2CESSeZcdqBLKFnBHfFpBPPfHfRxBfXTDLAfCBAPGLHARSbyBAKoBYkCiCeOYEBaBEDsDHYAkBMYoB+BekCUcgBUUCUMJUASIMOhB0NEAMXEfZWEGAYrCgNCwGiCoVOCaNINAVDBGNPbRCZLLJALRtBddwBzBQASNEFAHNNLBTapBeDBAFGNOLERGHDHPFFEAFIHSdoB7CAPNXHXP9BHTDXEHMLqBNCDPBDBXABCpBBFGCcGOAOEEG2CEQSeAGVYtB6BFLAPBDH5BDDANFPPLrBLpBZNFfVJPDLElBGLBDFATWHYPYAMoBWqCgCaMaEBaDEBsDJYAgBKWyBqCUuBSeWWeMOAQKHOAYQUtC+MC+FmCiVQCIDQLKXDFEXFBJVRCRFLFLLALRpBbZOHgBdMFQEOLGAEDBPNLFAXUxBYXSDBElBOTAdepBsB9CDTTjBHlBRvBDfMJmBNGHRBDBFC3BBFEAYGOGyBCEE0BESWkBrC0CV3DJNTHbFzBdfTTTAhBEDANGLHBVWLaNWAGGGWKUO+B4BgBQaEDaBCAgDLuBCaMYsB+Be+BMSWWaMYCIGCIFMAUQUtC8MCsGoCgVWBUPGLARDBERPZLADEJDXLJJALFRLVJJBL8BXMIaFEDBTHHLANIjCKLGNOPPFLARFVkBhBQVQXoB1CANZrBjBnDALIHgBNQBAFFDDEFDbADEHDdADEAYIUEYCEKmCIYUevC2CDhBX9CTPjBJTJ/BpBPPAXIdGHBDFAPKTgBNODQqBc8B4BSMMGiBGDEAqEFMAOBECaMYSUaqBESGKKMSiBgBeUIOAYMFMAaKQtC4MCoGoC8UWBUPGNANDDERLLDLFDLGLBXLFHALJXAhBiBBECUAEGAGKGMBMCEJANFJbA3BRRAJGLUfdFLBlBDDwBvBYhBoBxCBVdlBAFZ3BFFLfCN2BXDDlBADCnBBHEASU0BQkCKYYa5C6CPrCT7BNLZFRHrCxBNNBFCPQdIJHDRKlBiBFIDMOMYQoCmCYMaIG2EDCAkBHMEIGASSQ4BUmBgBWGOWaWMUCUIGGJUEOKQIGrC0MCwGoC6UKAWHMTEPFJCRFBDPHFXCNFPLAXKjBIBmBSIICSYKMJERTJ9BvBXAJKJUvBvBFLAXFTQLkBlBevBgB/BBVdbxBtCLXAJEFyBXFDJCLBPGrBAHGEWe4BS0BOYYY/C8CJvBd1CPPpBNxBnBTLTRBJiBrBADjBMnBcASgBYiCoCSMeIEEGuCECCmBEEAcDEEkBOcSWMWMQOgBBIFHxB3BJRbXPMBSEEGBYOauBgBiBsBUeeuBOIIFSAMGOKKpCuMCgHsC2UQBMFKJGNANFJCNJRHHXERJJJGNYjBEBuBoBDSWUGFGAKPnCzCTFFCfkBJTVRblBATDDBVmBjBSXMRsB5CDPFHhBZJPfhBZjBALEDkBVGJbCTIZAJEFIGUUauB2CSQSKXWPW5B6BVhCdlCNNhBNLJjBfjBZFLDDgBbMFAFLADCBBDCLAZMRCDGAUkBkBmByBeciBQK6BO8BAOEEAoBCMKSsB+Ba+BPCjBdTLfjBVLLODSEEKBGGOCiCgCQKsBIYWgBISIAoBQUlCoMCoHmCwUWCIDQLGPAPFJENFDFNJHPGdPGNelB0BuBBSWWWVXZfvBPPLFPAnBkBHTZZZjBAVDDBXgBbSXavBAFe9BAHJPhBRnClCLRCFgBXKNXCdOZEHIAGMUegBgByBccUK9CmDDBNtBPdFTNbADTTlBRvCnCBHmBZGACDDDFCXAZKXCBUEG4B8BOYeccMGIQyCMmBCwBGUMUMMaoBOcGYKOBILABEdXdRRTDHFHLBFFFAHIFUIIGDUIqBuBgBWYECCeAMM0BWGEDiBOU/BiMC8GuCuUaAGBSPEJDrBFBFNDFXENFNJKRchB0BgBIIASWSOFIRvCtCPFTCjBgBFRnBpBNXAVFLALYXUdWnBcvCBPNLlBTrCjCBLcXOHCFXCVMhBGHIAIIOkBkBeqBccYMNQdsBnBuBLrBnB5CLNRHHAVLLL9BrBJNCDgBZKDADdCdKTEDEAQ6B6BSYecYIQKMwCMwBAiBGYISYaamBciCHEHApBfVTHLAHZVHAFEFKECFMeQmBuBcYaKkBCIKYMIAWIGIFSEQ3BgMC+GgDqUWCMFONGNANFJCNHFJPFDPGdPAHaxBEBKGuBMOIAEIMKCGGKAIHCTHHFE3CvBXAfgBDJ1B5BBfFRgBrBYxBMxBMdARNPfN3CpCBHEDsBfNAFCBBbKbENKIUwBwBUeaYcOAGJITmBnB4BP5BdpCRPjBHNJpCtBJNmBrBHBHGJAlBULEFICKQSgBWwBwBeSeGG+BEECgBGSA0BCEAMQeegBUcU2BDC1B5BFHDVRRNAFGFSeYasBiBmBeIMAaasBQIGDGAaOUrBgMC4GuDkUcCMFOPCZDFCDBBCLFDJRXCRFLJDFAVKXALEDaASFkBAGGcCINDPDFbEDCFBpCDRGLODIDCPLfnBAPJXAJclBQnBctDJTpBPLLrC3BDHsBdCFDDREZKdEJIAIGM0ByBoBuBYOQERYRmBViBDAALLvBR7BLLLFfBPFtCnBLJBFIZGNKJHD7B2BAKSQoBU0BqBYMiBEAqBCCAmBEEAmCDMECAQGMAIYaQyBMWgBgBEMOUOOSIYEWKDkBGKd+LCqGkE+TYCKBQPCJBjBCFHDJTXCbLDXDHDRLVAHgCvBUDQHEAIHAHRTbYlCkBTWbbDFATHXYlBU3BGlBCBAPKfDTLNjBL1BlBZNPRKLiBZDDREjBONAHCHICOyBsBuByBYOSEEEFGhBmCDlBBBARDDARHZLJHBjBALDnCXRHJJA1BCFDAPSZ4BWOOCeQ6BiBUGcBBkBBEDsCLqBEmBMUQSiBsBUsBAGUkBUSSKcCQGEIFOAMMUN8LEiG+E4TOCIBUPGPANFFCDANFBFPFFLElBLBFCXrBpCAZKZIROLELIHAFDHFAFFNEDECGHSAIJIATMTAXHHFEFDGVANCDErBGVALFLNJZFRJdThBRZTKLiBZDDTEhBONAHCHICOQSwBiBSW7BLtBPNLALBDAlBCBDFPYT6BQKiBKkCiBWGeCHYAMPuBAKZkCAUMagBkBUekBsCaYMGUGUAQGFOAYUWS0B2MGAAdCBAVEBBfRmBIkBC4LEuF2FwTSBUPGRALFFCBBBCJDFHRPABCjBNClBLZH1BMfALIfGLOLKVHLHBFCJBDEAQFKAKTmBPqBAMBCCkBDAhBhBFfFLALQbMrBCnBEBC1CPPlBHRLpCjBJJCDMFOPMDEFBDVEXKjBGDGAMGIXsBAGIIgCWwBcUGaAJKNmBXsBfyBDKAaEI+BwCgBmCYaSImBEQGDMAYKQIGOd+DGAJJpBdDCAMKMUyLEkGoGoTMAQFKJGLCRFJELFDDLFJREhBNIRAdBBCjCSRSZWVMAUTCFBFHFRFPYbWlBmBJYFsBFAPHlBnBALHZANIVAHUdkBrCGVBJNNfDDRTNjBFtBVFABHGLAHIPDDhBkBVJDFqBfAFVEXKjBGDGAMGIQOYKEGDIOOmBS4BkBbkDZeLUBMCYBAPVJDNKDQCGICWSgBwBiBckBkBKSSUcKcASGDMAaKQKGOQ8MGCAFfhBDJBKEGoBqLCkH2G+SaCGDQPGTDFEBFDCBBDCHFFHTDBDCNAZJMXGlBOrBkCdWCKFIAEDBTNLTQ7BMZMJKd+BLNXLfdFRALDLAN0B1BsB9BGNAJFLPJjBLhBVRVLFHALJBFGLafDDjCkBDEBKjCTJHqBhBAFTETKlBKHIAGQS4BayBiBSGcAFWAODCAQBCAQLoBAMHUVcFUEEAKISYYeqBSsBHCBDbBtBbRLPPDHVTLADGFIECDMcOqBmBoBayBSeGQMOGyBGCIFQCQQSgCgLC0HwH+SUBMFMRAXBBCPFBDRFDLABCbJSTarBabiCAGIeEILDVnBAbHjBDTK7B+BJTNLNFhBfNtBoBZcX0BzBGNAHFLbTVVzB/BDLmBbGAAFbAbIXADGEWiBwBUsBSYUOhCoBBjBBDATFTAPDBBhBDHJJLFrBAXHxBJbHFFqBlBBDHArBYXGHIAEOS6BW4BeYEECIBOAFWAcDEFsCNaAGHMDgBKSUWamBMeIiBKMBE9BGrCfRXRFFADGFWKIcIcWyBYQACC2BACBkBDSGgBAICCIFQEUKMIG6C6KCyImIiTQAUNKTANFFEBALLVDDRERFCFYPgBfiBXMGiBEWGCIUKKAGHGTFHXC9BZdAvCyBRbPPJBnBrBBXDBCHGAyBZ+BvBOPAVdjBRvBNZJdCFkBLMAAHPDZAXJPCAaKWMuBEqBKYUYXGhBSVGJGDDAXBDDbZ9CJLPFrBENF1CNHHQNOXGDBDHAFGFANOjBSHIEMGISIKAaMYGaOaKoBAA6DECLeAILWAMIWekBSeOgCGMKGCMdOXGJEHATHLALFRBTNBHHHNFPICCFGEEDKGGsBOWO2BSwBHiBLQJoBBUKFMAYCGIKIG4D2KCwH8IqTSCOFKJIXDNCPLLBLNAHCNHEDgBNcTiBRqCOgBUULAVDDAEDCBBDGLFJApBVZHXArBSbOPEThBvBrBJRFXAH8BZkCvBGJERTnBLnCFNAjB0BAAFVLTDZRFAHIC0EECAMSeNCnBS1BOTlClB3CFHPFtBERFhCHTFDFAFatBHBnBmBPKFGAKKKMGeGsCgBMEqBBM4CIgBASFMAOHQASMWaiBQcIiCUcLM1BaFAjCRLHDLLLLDDGJCBMCCBECIEESE8BemBMmBJsBTSLgBAUKFYGYKK+E2KCmH4J2TYCMFQTAXBBANCDHFJRXCJHeJkBTeJIFyCGWGOKSDKJANDDDILALFTA9BThBAjCYRCVtBVRbrBDLCRODqBTgCvBOLCXPjBJjCFTAfEDuBCCEEFXPPBZVNCDYCGB+DEWMUbIbO7BSLhBPZ/B9CNFdABEDDNAlCRdJDFANOpBBDFAPUFObeAMQKuBOiCgBYECCeAWmCayBBkBDCAeqBgCGSCiCScNMLClBUtCZLNAHRPPEFOCEBIWMyBgBoBSoBDmCfYCSOBkBGMsG4KCsH4K+TcCMFKJGNARFFCRJHHNXCHFCDkBLgBRsBPkBACBWACDkCEMFMPDHFALKHDlBEXFrBDtDaDDLhBNPfzBDdBDYJiBToC/BCZXlBN7BHTFfEHuBAEEEFTLbFdRHEBGAaGSAWCCEiCIgBSYPExBarBSnB7BxB3BLRNJHDZADEXDNFlBFrBNNTAxBDANYBYRgBOKgBG6CqBMAECkBAeiCkBwBAYCCFKAWgB0BMgBBmCIMEOPMxBKhChBNNBTPPLCHIBUKE6B2BoBYmBAaJYBIFgBCUUBIAegI6KCgImMkUUDQNGNANFLELJFFNDFXEDDCJoBPiBRiBLiBB8BTqBASFQNHDBCJBBCpBANG1BAzCWXIPCJjBNRdzBFjBsBdoBnBgBnBCHBNdpBRxBNdFXADEFkBLOACDDD3BFPFHADEDQQsBO2CSgBMMVKhBYnBUDBFNblBpCzCLFTADCrCBDDPAjBHNNBrBDHDBJWAYLYBOGIwBG4CcaAWFW0BuBmCAcFOESISUaMeAUBEDiBBEIcAMnBABCLBBCLA/BhCENNZLEFDJQAGSSmB6BccOGWACEwBAICSFYGQQCKBGAeCEOOuJ4KC4H8MkUWCOFKJGNAPBBCVLHAFFJVCFFAJwCnBkBLUBoCjBiBBmBNPFLCLBXCTILAPGhBGdQpBITKRAJfLNZvBFRBhBmBjB0BpCATHPVTnB1CFTAHIHiBRGAAFNADBtBCLBJGAMSqBU2COaSSlCyBXvBhC/CJFVAXKzDCJFBJAjBDJFBLYAcLUAOGEkCECCSAUGQACEYAiBJAMSyBgBgCDGAYHOAYISeoBGSBmBFWGYTBvBPDPLRNhBAJGHATDHFDDEFFNGDOMUCaO2BGMMKWMwBOUMQAgBMMQBqBIOyK6KE2GkOoUGCUFONGNALDDERTbREJJAJED2CrBYHIAYLgCnBkBDIFKAQHVHFEdAXMnCWXQ9BUPADDAJHPjB3BFRAXFXejBarBQhBFRddLTjBnCBJCLoBTGACDPBDBVADCdBLGAMOea8CScWSlBiBVhCRjBFVLNXDJGbKlBCVGNADEZAHFFxBBHDBHKBqBLeAGEEGCgBAEBwDCWFGgCCEI6BDMDSLMFOEKAgBbgCBaMSiCiCmBMWOEUFSCMKQKGU6KoPEACHExBLXPPDEFYASFWwL+KC+GiPiUQCQFKLGJAXDDELFBDLFJPCLFDRED6C3BiBL+BpBaLWBULGAIHJDbAVGPMNC7BYZSdIbQPCFPdpBSPAJFBCDDDLFFAFIDDAZFRCZKLa3BGRALLTZZDhBJJLDXxBCHoBTGACDPBDBVADCfBJGAKcmCAGDE9BETGZDDDAjBCHBJHFNYAWNcAKKGME6BAECkBECCoBADCFyBDQFiBLQFQXYDgBKWkByBLMJSY0CQOeGcMCMFMAYMQIGsMgLC6FgQ4TWCMFKJGLAZCDFFDTFDVAHHDFER0BpBiBGIJALHHGHqBRYRiBRoBLMJAFDADCBFFEFDRERIHI/BW5C0BLErB/BFTDrBYdUpBMnBALGLAXHJJFnBBVJLAHJXlBNjBqBVGAAFNADBtBCLBJGAKOcAKFGBMXYAISQKAmBOagBQMzBwCdcFMAQBCCEAOMYaiBKSA2CIYQKeCUIIIHSAWMSoN+KC8GkR+TYCSLKPANBDGLJLBJFFTAHDCDGCwCAUGQKIAKPAFFHLGLFRAlCRdECHiClCmBVmBhBaNYBWLDDXFTELIFA7BexC+BFAPTThBAzBoBRiBhBajBCTJPXRrBrBPLXVBHiBZIHBDTAVMbCHIGUsB0BYmBcaAEXQvBUANCBEjBCBBdpBrBpB9BLZCHsBXCDpBBDEjBADEAOWkBU4BUmBeaAKJONsBd4BBMCeQgBgByBA2BCCAUKcSWMCQHMAGEEIJSAKGOOOuOsLC2GySwUWCKDKFKVyCDQKKAIHELNHXAFEnBLjBBNVVAPLBXCDANKRWlBchBYNmBhBYHOAYJRHFETFjBSDAzBc5BiCFDThBAlBsBHaJqBdMNEHDVHNNvBhBnCALIDwBFAFJFRFNAjBLFEDGAUKWIiBG2BUyBLCVIxBGBCVAPGBnCDBBjBFLffjBzBXzBWXWPJDBCdERIRCDGAOUgBW8BOckBoBD6BBEDmBBCDgBBECqBWoBaqBEeCCAaMqBIOWWMGMAKa8PsMEqF2VoVuBBEBUACDsBAIFAPLJVELKzCDBhBLVDDVAJFHNGVCpBelCiC3B2BLFHhBDDLAtDBBATCJIDwBMGBAHRTXHdRFCFOFgCLoBA6BCKVARGRABEpCCTKlB7DHNdfLXTdTtBDLELcpBDDHAJGBBJCfgBDKUkBcyCMWacGQI2CGUG0Ba8BWeGWAqBOwBYeWMGAOOKEgBDMGOkT2OCAGNSXELjBAAmBuRsNCyGuWiW2BCEBgBAUFMAECGJENPNRGRSLABD3BFDBTADDGPDfFBLXREHDGPCfEBAhBFDARMrBwBFoCVQRCHEjBQzBEXGLEDMAOIGAGGMEGGEDALFDEBDJpBdLFHAHIRsBjB+BAKDMFCTFxBaHBhCABCLARKZnBflCjBjBHRpBxBTjBBfITAPDDDEFDBKDFHGBDHUAiBYqBAGcgCoBuBIQekDYwBCOkBiCDCAiBBCAmBGUOcOMWKMISEaOiTkOC+G4X4WkCAMBKCKJALCBJNLAHERQHADBNAjBHLFLALLKTBfPZPAGJCZKXARFHFXCNGJAHWCEC+BACBOA0BLMNKdsBrCKJMDyBcCJFJCBBJnBhBFBPCpC0CJQBOJQDBjCDBBjBDKPOJaBGFKAEFHDFENFXA3BoBdEVMblBpBjCVLRFHJdPrBnBJXFxBHDDIDFFEAGDBDIAaIkBKKGAUUuB2BSMYKWwBCOOaAGkB2BGYSgBFMAMLmBCmBMaQQSKqBcaMyUwOCuG+Z6XIAMRAFHDCDDDRAHILExBXZTAFWTAjBFBAFJNHDGHGdITB1BINAJEASIkBGCCiDBQNQbadSZSTGBQCmBeGHFREBFDFLbdLDzBwBbSVWNeHEXJzBHxBRdBCJWZUAWJDDRATFrBoBLGNOBIDClBnBRZXZFBXABCbBBDXBZLNNTxBHDBKFDJQAGWyBOOSA4BgBmBEoBqCkBqBIgBGILYAQHQDcBCCeMamCmCoBSkBISAiW2OCyG4YsYKCQJAJFFEFFDNAFGHAfbNRDHOBMFKJGNAPBBCJHFAFJNKNMvBARCBBTILGVEAMI2BO6CEMFKJGLaZoBlBSLWEmBiBEFAVJNHHRdJDLGXU9BgBRQVcFATHjBFxCdvBBLGBFYlBEDQAIFKAEDBDjBDBBJCrB6BLI7B3BXCPOVEDCXALFffNFHKEEDCEEDMcYeSgBBUGSAQFcqBsBqBGSAKPYBaFKFYCsBQeCOSgBaasX8OC6GsXsYSCONFFEHFDFAFGFFPhBALiBCQJGJEHAXDDEBPVMJGLGpBKdANILKXSKKAsBQgDCqBnBYPWTiBRUGkBeGAEHDBEDFBCLFDBHXZJLLAjBYFATMlBQpBoBfLrBHxBTjBJhBAJEVSBIHDBJGHEXMdQAGFIAEFADLADBLCLFDCBGCGlB6BBItBdREJKFSJKLGLAZRRHJAAECCFKGMBCSOyBSKLcFMJaccSEgBFGHWAaJUE0DIUae2YkPC+GoWgYQCKDEVFFAHGRKLSOgBAUPGXDBAPHLAFUVMhCYrBAPWMMAoBMgBAECwBAIBCCSFgBhBuCvBMACBECMAsBaEDDBEDFHCDBHpBlBLAjBWlCWnBoB/BLpCXZDDBfARGRQDOFCDBLAFJGPCfITAJSFGHDDdAHDBIKIb2BFYbHFCLQDYJKTBlBRHEGGFECCBGMEJCGEBCWKwBKGFEJQBGFGAWMGeLWAODCESFMAsBJKToBBMAYCGDBDICMgawPCmGgWoXECCBECkBlBcNWWKEYDQLGLAXBBCFFDAFYZETGLAParBIdQISAWGkDACBUAUNUXuBhBgBPKDaAsBUCPFNnBbNDPMVMpCalBoB1CL9BPXAFBBCbAZQJQAIDIdAJZAJCDEpBGVCJMLDDrBBAGWMZ+BDYECCcHIDMJIRAlBRNDFGGGFCAIGMIGwBKQAGFWACBEEAQHOBwCTKZUNONWFCDBHICIIIqbgQCoGsWuWMCqBXaBEDIASYICcAEBSPCJAbSROrBWXKXGRALGDGEUACCoCACBaAEDwBFWRGLSTwBhBoBRWAoBOCNHHCBPNlBRfY7BaFATMVWJQ5CBBD3BBDDzBEZMPSDYHIBDRMHHHbLXEjCCBAPGLAHhBBBBRCCGQEQKVgCAYECGoBIWDCTFvBXNCEGDMIOQIyBMIDKGAIFMAkCDGXEnBSPOFAFGNFHIAIII0cwQC2F+amWaAMDKLGPDJcXQlBUDOJCVMVALEDoDJqCRWRGPMPsBlBcRgBLYACEaCCDFLHBCDFBCDxBPjBe3BaRMVWLUFGnFCDENAZIZWHgBfARVbvBELDrBEDAbCFFHFErBDBEEGKAOIOCP4BAmBUuBJAVRVJDCCKDCCEBECMQM8BSHUDkCDGfABChBCNKFFZADEAMYQeBOFgBAMCWYgegRCsF6bgWeCGDONCNUJQRSZKDUESFKTATBFGLAHEFwDZ+BXQPShB4B5BYNYJsBECHDFJDCDHHtBJdehCqBXYTiBrESxBMhBUTiBrBFPNlBxBFjDDDdADDVEAGsBMFwBBCAkBGMDCDDFKDKECDEEIMKmBSKKJYDMAmBJUDDTABBVABDJEJPLADBLEDMWYMAOGWASGMIAGKOyfsRC+E8cgWQCMDWTQFWPcfyBAMFQdBLFFAREDoDpB6BbONIRENMViBtBWVYP4BBDJJDFJxBLJKDKXYdYhBiBLUFWFGpBK1BSTCzBSnBUZgBdHnBXxBvBHfH3BHHZADBHCPBFCAGMASIWGAoCEEAMcyBcaLqBAUNahBPELHPXDFEDQGGIScYSGIKAIGKOKkhB4RCsF6dgWYCMFKJoBRuBhBiBAgBJOPMXDRJJiBZ4CzBkBfKRCXITwBpCgBV2BJNNBEJJ3BDFGDQNU7BgCNiBDUDE3BaFA3CsBpBcNORBtBXbZRbDFFAHIFOAKGIYaiBOSMCGdFRLjBnBLRBNRlBJfLP7BAAEWEQISCEwBKiBkB4BacLsBAMJQNNKRFXNABCFBNGAMMYCUGMMKBICYIK2iBgSCqF6egWcCKDKLSBiBPKLKBYRsBBaLUTQfELLT6BzB+B/BKRATCBEXa7BSbcZUHaFGDZN9BCDGBW1BqCNeJsBJKxC4BjC4BJAfLlBTVTLVLPRcGQUWGAeQyBiBLMLAZHXDXJzB3BFRTlBFTPZFB3BACGKAYMMAKEGqBGMCQMYmByBKKKGAGFFFADKFJPOMgBFMAeLUAQKQokBiSC6EkgBgWeCWVcFYLMLgBTqBFYLiBdaxBFRJH2B9BqB9BA3BWzCKPMReTaJHJTDpBMLAFEDGEQFSjBiCFSDYBEAiB1ByBhCiCfJlBVVRLVBNFDDCAEFEECDGHKCYIGYKSMyBmBjBmBhCLZLzBzBrB5CJL/BDCEQEcOMAEGKsBUuBsB0BOMICLyBFMPOFSHMAUGM2lB6RC6FwhBgWYCMFKLGLgBJSHsBlBsBLgBRgBbiBxBETHJNFDHiB1BezBCTHdAjBCBAhBEBCfGRMRUTcRHHBEDDBEDDRENIjBODIGMAILwBHUAKFMAUDCG2B3B+BXkBFApBZVVBFAbJEPQFAFIDKEEcO4B2BAGhBkBLSNKTAXFZAVH3B3BDLThBLfNRVDPCTFHCCEOCcQSEM2BOiBWckBkBQIN4BPQPkBCYOOgnBoRC8FijBgWOCOFONGNDDCDaJUJwBxBUFwBXkBX8BhCDXLJbLFHaxBAFUrBBXJNBXDBBhDSnBgBhBBDNADEBD/BmBAIKOAQDCAaBEASFYAiBOwBtBgCFEHHTbYTBFFBBCLANKbADEAKkBiBUeAGZqBdgBNaPO3BALCRH1BzBFTPdDXLTNHXABBDCLBHCFBHEcGSKWCK+BIaakBccUKFuBFSLOAGNcCaOOkoBuQCsF0kB8VQAQLKNARILKFMDWRGPMLQXYLOLsBReR+BzBOPDVJJLFVVXfW3BATXvBDZHdARDBAlBGLAJWhBIJBDFATMvBiBAIIMAMEEAkDIcQcTADBNAHIAGQUCMf6BFSTgBRWLcTaJGjBCNKPD1B5BZ5CTPNALFJGXASGWMYEEyBCCAQGUgByBUWOIDgCRmBFGBSGOMOkpBuPE6FgmB0VUCIDQPEXIHFLsBlBSrBgBJEFANFFMNSHWDsBTsBdONSHOPAPXZJRNpBHNFXEJkBFOHCDZHFCfALFHAVXhBjCJfAVGJiBhBDFxBWRENKAIMSKYU4CMWYWJKhB4BX0BlB4BPsBRYlBOLMFDnB7BDTNrBBhBJTXVBIIIAEhBNDCEGJAGGFCQKFEWMWGAqBCCEkBa8BYgBCIBMCEEyBLcJMAYMQO6rB2MICuCbRhBNtCPoBFYiqBoOC6G2nBqVQCIBQPGLBJMLFFAJMVWZGNARgBPgBFEDELHLTBAILERMDDGLiBhBuBL2BZuBjBSJOPATPZHpCBDAVEHIBqBDKJTHfAjBLFKDmEMatDkBHAejCe1CANFLjBdzBrCJVOPgBPEFBDbEXIdAFIAMiB+BSuBSaeYRUrB2CdsBNkBFgBLYxBiBBDb1BANN7BAlBFLNRASZVDCKORLBEGGHAGIDGGGUQMGA4BECCgBMaGYOcGQEeMgBDWRcASEKKKIG8qBoNC+GopBqVYDQREJDFKLFZMXONIRAZiBVYDMFKAEDDTRHJMNKZIBHINabmBLkBRmDpCELARDPC5CIjB6BBEDDHFAFDfFLJRFJOFuBTkCAqBCM/D0BAFKVS1BW1CJPdTtC3CBJeRQDGFFDJEJDjBKPDPIAMEMYcqBoCYYWKPYVqBHalBmCJcAOFYLadcHCR1BB5CGXFXFBBMDJPPAMLLBEGKFFFCGGFGMUSQBWDEASBCAqBCCGwBMmBEkBU0BDSNaASOU8rB6MC6HuqBwVMCQFQRCJBLILFFBVMXONGLEJAdoBVUAMFMAEDDTJHHAFKrBSJBGLelBmBPkBXwCnCMPEHAxBO7BAPMhBWAECWEKGEBAFHHfTXTHANSHmBFKJcNcFUASBCCEAY9DiCAHIZK7BCBEjBCBAVCBBNJNjBRvCtCAFGHcNOBCFFDHELDNGpBALIAIISegBiB2BaYeOTqBZ6CX4BBgBJeFMdgBJlBAXCBCrBKdMTCbDFBCFBADFHDCHBCIHBHGGcGIAKRsBH4BCCAmBGWE0BUyBBYLUASGMKK+sB2MEsGyrB6VQCIDQNGJAVGLFBBTLFSPCHSRIREjBEDkBLuBAEDARJLFALIPGjBEDCADcvBqC1BwC5CGLExBOlBMxBMXMBiBMKKGBAFJLzBvBFALMLkBrByCFWAiBDGvDuCBRCDAnBEDA9CFLJJjBNvCpCDDGFkBVGFBDdEdIVAFEAQKOgBgBeqBcciBQVwCAWBEBkBDAAJFHDBDEBJFEBDFKFFFSAUlBwBTqBAcCEEsBCCEuBSuBASLaAcKMYorBoPaXMTKjBClBMbBLFQbYLSPqBJMkuB2ME+F4sBgWQCMDKHMTDRGNHPAHHDLCDDEDWFQZIFMTCjBGDWFYAGGYACEMNDRHFFABGLABChBABBTBkB9BaTqBpBgC3CGPEtBiBtDGDIAmBOGGIANVxBtBPORwBf4BLgBBsBrD8CDAFvDDDATFXPPTFTLbXZRXboBnBJBXGTMRCJICSwBwBemBeYaIAUFWAWDEA+CHSvBkBbcFMAyBGYAgBIeMYAgBLaAMGOKMQusBuPeZINGVAREBBN1B4BqvB2ME6FguBgWcCSLINCHBRGJJLDPRAALEFUBadMVAdCHeBEEMAIMMAKGMNBBCDALDDFDXELFbFHDAJe3B4BxBWb2BvCCJB3BCBGxBEDAPIhBGDOAgBKKGEFTRTLdZJGFMFeNsBVyBA+BhD2CNKFBJvDLrBNNjBH5BpBJBVZMbQXLBZOhBmBIOYQkCkCUMYEAWBCC0EBCBkB5BeJMFMCkDa+BBaHUASEMO4tByPGAahBKTBPtBiBGUywByMEuG2vBgWSCQFKLGJARDDGNHLCDFLRABJKNQBYfKRAlBGDmBOCOEEWKKLCTDDHAbPNJXLAHOZIboBdaZmC5CGLARHXA7DCHOHSACBaAECCDHHrBLVJNADEFkCN6BAmBGYEKjDwCVMFBL7DFVFJPJRAXFjCjBRVAZGXBJPGJKFMFaHSCGIIkBS+ByBUIWCBuBDEAsCEGDEAsBBCCgBzBcPSBIAmBGYAkBCIckBCMAUHUAaMSMivB0PIFUdGPBLpBiB0xBuME2GoxBgWWCMFMNGTFLGPFFFRFDFEJBANKNOFIHGPMRAXGNGFYQOMFMCGOEIKSPAL9B7BLFPBQfGXiBZiBdWZyBjCETLbDXBBBrBFXAlBGJMFqBJEDHDzBBPFNADEDGAMECAqCDCAkBBKCCEaMcxD2CHBELApDDBBXPNJBhBA7BTXLPPFLHvBDDFCNSEiCGIMAgBO4BoBSGcALyBAQBCF+BJgBAqBEMnBYXaDIEiBIcGqBaaKSAeFMAUKQMkwB6PEAWpBEHBPjBkBwyBqME6G8yBiWGCUFONGJARDDERTbFENBARIJIBMLOnBSfMGUUGIFKAIIIGAGIMBKPAFRRZrBNNLFHARQBZMXCRGJmBbYZcfsBhCCVTtBANR/BBdCHIHyBTDFlBABCrBBFEAYGUAkBECA+BCCAMSoBXQnBiBfYBPEBAVCBAVEBAdCBBdTPtBALF7BNRJPRHjBARHBLQDMAqBBCAMEIgBGyCsBsBEPgBAKHULyBNeDMAyBxBwBNWGkBSsBGagBeGMD6BKSMkxBiQEAADYvBBbjB0BszBqME0Gm0BmWKAWHMTEJFPCRFBFNFHFCNABVWXKZYnBWUQUFMAKSSGFGAKLAFNRd3BPPFDNEVWDrBMVERGJYTmBnBQXuBpCCPFPLNXrCFJFXAVONMDMHSBAFDDLEBDNADEzBAFEAOQ8BGkCGQUkBPKrBqBBHGLALMnBARNPFDlBAXF/BTRHHHFNCzBFALQJYAILYAMKGcGuBYgBWuBKxBmDLMLUBWLMFgBdmBPkBCYmByCmBmBAMECFYCUOSOmyBoQGFQzBAnBHId+BAGo0BsMEiGm1BoWaCQJMRATDDANEDJFJRLCLBDJALSRMfYlBciBGMAKFIIQGAKIIBOPRZAFXvBTVPBbaDBFtBMXCRGLyB1BYhBqBtCAPdvBLlBHNPpBANMLUHGFSBAFDDLEBDNADEzBAFEEaMeQgDdFvClBVRBDAdCDEVGFFFRUReRUAIEGiBOyC+BUIQC/B+CdcLaJCBDLIFABICeTsBLsBKacwBKUmBmBGQDoBKQUmzBuQCAAHQrBB/BPQLwBAOFMCKi1ByME4Gy2BuWOCUJORAXFFCRJHHNTEHJAPOTKZSXCJGBemBGMFUGOQGIDKLAFNTAFZ1BNPLHLAbcLjBATQjBALadalB2BrDDVblBPlBTlBJbADONGASLOBEFDDLEBDjCEHGAOFDJKHCRSdSDICIuBqBwB8BUOUI3C8CRKPQHODKAmBGUAmBBEASDCDkBFCPTELAlCMbANDHJJFEFBBGDDHIKmBDEFoBBEAUDEEcSiBaiBIWaSKOGOBkBGMKKU23BiFEAAJDBBbZpCPSNkBCKcc61B2MCmGw3BuWcCMFOPCJAPFFAVVVRGJLAPMTIZSdEDmBqBCGBYQSOBOPZlBVpBVZFBPCXcNtBAJQlBCT6B5B8B7CDTlBjBfvBd3BsBrBDDLGHATMHBOJGAEFYHEFADLADEBDLATGlBAFIESGIDSYmBMwBOaYaTY7ByCbUPSFSAaGQEgCDEASFWRRAJBDDfBDAVBDANERBLFFAFJHLENQSaA2CGUYoBUWMcUMSWG2By2B6MCyG24BuWUCIDQLGLAXFFATFBLRJALGLPALGLCTYvBEAuBqBEGDSUSOFKPZbfvBPPLFPAVaNnBAPMbCTgBVkBlB+BzCAXXlBBRX/BBjBGHwBTCD5CAFGAOKYGyBCCAgBLJrBnCLZAFONgBPEFADLEJDZKdALGCWKKSoBU+BIOgBePUxBsCtBsBDMDKAcGSAWCCA+BBCASTTDTHVFhBDDAdPVHAJGDMFCYaEyBKwBiBuBQSAKGMuBoBCKAgBOUo3B8MC4Gy5BoWcCEDSPGPDPFHAPVVFAFGHAHFFPGLGnBOdIBsBeKKAOWUGAKJGNXT1B1BTJNAVWLhBATIREXEFeRyBzB2BpCAXJZA3DEFWJqBFDFHAJFlBFTJFADGDGBgCDEAOLyBEkBIahBWAHOlBANHPjBb1BpCHVWVSJGAEFDDbEJGpBEHGAOSaqB6CceQKRUvBuCfgBNYDmBKYCuBEEDuBLFHJFXNfJzBPRHAPSAGWWGsBQuBiBwBSSEOGKiBcMcAag4B4MCiHu6BiWaCIBQREHAXJNEJVVXGJPANGRAdMTAFQCyBUIICMWMIBMPDDEFFDbLXRvBZLBJCLOLVBTMfAPKJULiBdWX0BpCEHAvBapDKJgBAEEYAPPfNXRFAJOHmBhBkCHcAuBzBqBBHSzBBVPPRHTTTZZZPXAFMJkBZDDXEdKZEHIKWcoBe4BQSWQMERYnBsCLSTULUDWECASIYEuBCEBmBFCLPX7BFXARFHNNHAJMFKEIUOM+BOiBuB2BEOMSgBeISEgB64B0MC8Gq7B8VcCKFMJGNARJLARHBNRTGJJDHGPEhBCDALBBCTIBOGyBIIEEMMGIAGEOLATlBHNJzBTdAFGHNBTITEZKLUL0BxByBnCITAZcpCCRMZIHSAoBOEDRRxBlBJGnByCJQPeFUBgBhC6BFBS/BAbBFJJdNjC9BPTAHONeVDDVEPIXGPAFECUeiBqB+BSSSMMEEGLQtBkDPONaDWQ4BCqCDAJLDPTtBFlBLRFHPGJUaWGsBSyBmBuBEQMWmBiBIWAYGK25BuMCkHw8B6VMCKDWRCdHLANVXRKNTKhBAPCBAPHZKE4BACEMAKMYGGBGLALDJLCBBVApCTVCHRALGLGfiBViBhBURSbgBlBGLAxBGNGrBCDAPKhBIFKAECaEMGEBRVbPTPFAJMN4BdkCD8B1CiCBNEBIhCEBAdDFJJZJPHlBfXPVVAHUTSJEHVCpBQLALMAGIOkBgB2BgCSMYGPkBdwCTeJWAYSkCAwBFDFXFHLjBBhBLVDDREJMAGWUG2BMqBkBsBGgByByBGOAcGKKM06BoMCyHs9B0VUCSJMRAXDFCRHBDJJJTGNPAPIfAbJRoCHQMSAECGDETHNfGBBtBDBBpBAFZIZARIHUHeTqBrByB9BETJZAtCBBAjBCLGFIDYACBYCCFbNjBHHFLADEDGFsCLyBAaKkBlDmCBHEBCjBCDATEBCxBLTLFTBRJ3C5BBHafMJBDFAfOLKZIDGAKSUmBeuBsBaOYEAEFGHUZ2CVkBFQAWS6BGwBBAAJPlBBXDBAXHNAFNHFGFAFUUUEwBCCEeIYYaIsBWYMGUUCGAkBEIQQw7BkMC4G2+BwVUAWTCFAXBBCRHFJRXCPTChBEDAbFPJHIDYDOFOAEBGAIIMAEBOCEVFNXEDCpCABENAHPAPGNAT2BlBmBjB0BjCEXPlBLvDINSHkBJADDDNADBnBADDTADEC0CBCAeDCAgBGYMWZMhBepBaEvBEDAfCBAlBLRvBJ1CtBPPSlBMLBDFAnBgBVMFKMQkBWgC0BYMcENiBZ6CFGLeNIHKAIKGIQGsCKaOUASCEEYIQUUUIOOCGBmBGMKKo8BiMCkGw/BuVUCIDQLGLAVBFGNFBJVVCVTBFCJAtBFPJPKFmBPSACEgBDCPFNDDFATKjCKPGFNCzBgBToBjBQVyBpCATPlBDdN5BAZQRqBNADPBBBRADCrBBFEAeGWAgDIcMSZQhBgBdWDBC1BEBA/BDFRNpBF9CrBJJCXKZEFADFAbcJOLIHQEGyBciCuBYKcEPkBBUFMP6BNYBqBamCCeKgBASMmBWaaKOMCOFMAUUW88BkMCiGsgCuVcCSNKTDRGLFBFVDDNCVJJLBFAtBDLBHRV0BdIDIGKAGFOBCPNPFATOlBIpBQFNCtBiBZWVYduBpCEVTpBJvBLhBBdCHOLqBNADPBBBRADCrBBFEAaCEEiBCEAgCCEEaSeAGPKjC+BDBCFA7CBBCJBBALTPrBF9CpBNLAbKbAFFBXcZwBGGyBYoCwBQGcAHcRgDRmBAeoBiDCaMwBMWSUkBOKMHWASIQw9BsMCuGuhC0VWBUPGNDPKNFDFTDDRATLNNATDBARFVVbqBfSHCCSAGFMBCPNPFAXS9BWJKHDAVIZMLERWZclBSlBUhBCPV1BFjBPrBBZCHOLqBNADPBBBVABCpBBFEAaGOAWCCC0CYyBtCuCDBArBBDAZDBAdFRJJLFRAdJ3CrBJLAdGXAHDBTWZyBAGIImBSkCyBaMiBEHaDsBBEAUDCAYNqBCoBmBwCKmBY8BWWmBOKKLYAMGQIG+9B2MCqGgiC2VWCKBQPGPDNGPFFDRFDLEZNNNANBDFjBFLXVuBnBMFSAULCJPTJATW3BcDAAJITOLERGFAFHHHADDIHYlBY7BOZATTpBJvBLhBBdCHOLqBNADPBBBVABCpBBFEAaGSAYCCAiCIiBGGKYnC0CT3DJLTJVB9C1BPPBHAdCBEbHANMLeReAGIGmBWkC6BaMcEBYBCDwDHYAgBIYGGkBoCMoBOgBiBiBYGWOLUAWQSs+BgNCqGgiC2VaCQLMRALDDKNFFFTFFNEZNNNFvBHRXVuBnBMFSAULCJPTJAHMbSnBUDDIXSRGPDLFFJAADIHYlBOlBMVAFMTATTpBJvBLhBBdCHOLqBNADPBBBVABCpBBFEAaGSAYCCAiCIiBQYAGVUbqBVWFnBJxBARFNNNrBL1CxBLLFLAdCBEbHANMdiCIGmBWkC6BaMcEBYBCD0DHYAaGSoBsCasCciBQKaGOKLYAOOUs+BgN";

  var ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  var CODE = {};
  for (var ci = 0; ci < ALPHABET.length; ci += 1) CODE[ALPHABET.charAt(ci)] = ci;

  var FRAMES = [];   // per frame: array of Int16Array outlines (centimetres)
  var HIP = [];      // per frame: [x, y] in centimetres

  (function decode() {
    var pos = 0;
    function next() {
      var shift = 0;
      var acc = 0;
      for (;;) {
        var c = CODE[PACKED.charAt(pos)];
        pos += 1;
        acc += (c & 31) * Math.pow(2, shift);
        if (c < 32) break;
        shift += 5;
      }
      return acc % 2 ? -(acc + 1) / 2 : acc / 2;
    }
    var frameCount = next();
    for (var f = 0; f < frameCount; f += 1) {
      var loopCount = next();
      var loops = [];
      for (var l = 0; l < loopCount; l += 1) {
        var n = next();
        var pts = new Float32Array(n * 2);
        var x = next();
        var y = next();
        pts[0] = x / 2;
        pts[1] = y / 2;
        for (var k = 1; k < n; k += 1) {
          x += next();
          y += next();
          pts[k * 2] = x / 2;
          pts[k * 2 + 1] = y / 2;
        }
        loops.push(pts);
      }
      FRAMES.push(loops);
      HIP.push([next() / 2, next() / 2]);
    }
  })();

  var LAST_FRAME = FRAMES.length - 1;

  // Obstacle: placed under the flight arc, cleared by the traced body.
  var BOX_X0 = 244, BOX_X1 = 334;   // centimetres along travel
  var BOX_R = 6;

  // Each branch keeps the recovered pose and adapts only clearance and lateral
  // spacing. The measured ordering stays legible even at small canvas sizes.
  var ROUNDS = [
    { top: 45, lift: 0, drift: 0, pose: 61 },
    { top: 55, lift: 11, drift: 100, pose: 64 },
    { top: 65, lift: 22, drift: 200, pose: 67 },
    { top: 75, lift: 33, drift: 300, pose: 70 }
  ];

  // Flight window in frames; the body only lifts between these.
  var LIFT_IN0 = 57, LIFT_IN1 = 61, LIFT_OUT0 = 72, LIFT_OUT1 = 77;
  var APEX = 66;

  var SEED_START = 320;
  var SEED_DURATION = 3300;
  var CONTACT_DURATION = 720;
  var FAMILY_START = SEED_START + SEED_DURATION + CONTACT_DURATION;
  var FAMILY_DURATION = 3500;
  var HOLD = 2500;
  var FADE = 900;
  var CYCLE = FAMILY_START + FAMILY_DURATION + HOLD + FADE;
  var SEED_END_FRAME = 92;
  var BRANCH_FRAME = 44;

  function clamp(v, lo, hi) {
    return Math.max(lo, Math.min(hi, v));
  }

  function rgba(c, a) {
    return "rgba(" + c[0] + "," + c[1] + "," + c[2] + "," + a + ")";
  }

  function smooth(t) {
    t = clamp(t, 0, 1);
    return t * t * (3 - 2 * t);
  }

  function mix(a, b, t) {
    return a + (b - a) * t;
  }

  function progress(t, start, duration) {
    return smooth((t - start) / duration);
  }

  function familySpread(frame) {
    return smooth((frame - BRANCH_FRAME) / (APEX - BRANCH_FRAME));
  }

  function liftBell(f) {
    if (f <= LIFT_IN0 || f >= LIFT_OUT1) return 0;
    if (f < LIFT_IN1) return smooth((f - LIFT_IN0) / (LIFT_IN1 - LIFT_IN0));
    if (f > LIFT_OUT0) return 1 - smooth((f - LIFT_OUT0) / (LIFT_OUT1 - LIFT_OUT0));
    return 1;
  }

  // The traced body at one frame, filled even-odd so holes stay open.
  function drawBody(ctx, fi, lift, alpha, color, drift) {
    if (alpha <= 0.004) return;
    var idx = clamp(Math.round(fi), 0, LAST_FRAME);
    var loops = FRAMES[idx];
    var dy = lift * liftBell(idx);
    var dx = (drift || 0) * familySpread(idx);
    ctx.beginPath();
    for (var l = 0; l < loops.length; l += 1) {
      var a = loops[l];
      ctx.moveTo(X0 + a[0] * SCALE + dx, GROUND_Y - (a[1] + dy) * SCALE);
      for (var k = 2; k < a.length; k += 2) {
        ctx.lineTo(X0 + a[k] * SCALE + dx, GROUND_Y - (a[k + 1] + dy) * SCALE);
      }
      ctx.closePath();
    }
    ctx.fillStyle = rgba(color, alpha);
    ctx.fill("evenodd");
  }

  function drawArc(ctx, lift, f0, f1, alpha, width, drift, color, dashed) {
    if (alpha <= 0.004) return;
    ctx.save();
    ctx.setLineDash(dashed === false ? [] : [1.5, 7]);
    ctx.lineCap = "round";
    ctx.strokeStyle = rgba(color || SAGE, alpha);
    ctx.lineWidth = width;
    ctx.beginPath();
    var started = false;
    for (var f = Math.max(0, Math.round(f0)); f <= Math.min(LAST_FRAME, Math.round(f1)); f += 1) {
      var h = HIP[f];
      var x = X0 + h[0] * SCALE + (drift || 0) * familySpread(f);
      var y = GROUND_Y - (h[1] + lift * liftBell(f)) * SCALE;
      if (started) ctx.lineTo(x, y);
      else { ctx.moveTo(x, y); started = true; }
    }
    if (started) ctx.stroke();
    ctx.restore();
  }

  function roundedRect(ctx, x, y, w, h, r) {
    ctx.moveTo(x + r, y);
    ctx.lineTo(x + w - r, y);
    ctx.arcTo(x + w, y, x + w, y + r, r);
    ctx.lineTo(x + w, y + h);
    ctx.lineTo(x, y + h);
    ctx.lineTo(x, y + r);
    ctx.arcTo(x, y, x + r, y, r);
  }

  function pointAt(frame, lift, drift) {
    var idx = clamp(Math.round(frame), 0, LAST_FRAME);
    var hip = HIP[idx];
    return {
      x: X0 + hip[0] * SCALE + (drift || 0) * familySpread(idx),
      y: GROUND_Y - (hip[1] + lift * liftBell(idx)) * SCALE
    };
  }

  function drawSeedNode(ctx, amount, fade) {
    var source = pointAt(BRANCH_FRAME, 0, 0);
    var pulse = 3 + 6 * (0.5 + 0.5 * Math.sin(amount * Math.PI * 2));
    ctx.save();
    ctx.beginPath();
    ctx.arc(source.x, source.y, pulse, 0, Math.PI * 2);
    ctx.strokeStyle = rgba(CONTACT, 0.13 * fade);
    ctx.lineWidth = 1;
    ctx.stroke();
    ctx.beginPath();
    ctx.arc(source.x, source.y, 2.7, 0, Math.PI * 2);
    ctx.fillStyle = rgba(CONTACT, 0.7 * fade);
    ctx.fill();
    ctx.restore();
  }

  function drawObstacle(ctx, familyAmount, fade) {
    var topCm = mix(ROUNDS[0].top, ROUNDS[ROUNDS.length - 1].top, familyAmount);
    var bx = X0 + BOX_X0 * SCALE;
    var bw = (BOX_X1 - BOX_X0) * SCALE;
    var topY = GROUND_Y - topCm * SCALE;

    ctx.save();
    ctx.beginPath();
    roundedRect(ctx, bx, topY, bw, GROUND_Y - topY, BOX_R);
    ctx.fillStyle = rgba(SAGE, 0.055 * fade);
    ctx.fill();
    ctx.strokeStyle = rgba(SAGE, 0.34 * fade);
    ctx.lineWidth = 1.15;
    ctx.stroke();

    for (var i = 0; i < ROUNDS.length; i += 1) {
      var rungReveal = progress(familyAmount, i * 0.13, 0.42);
      if (i === 0) rungReveal = 1;
      var rungY = GROUND_Y - ROUNDS[i].top * SCALE;
      ctx.beginPath();
      ctx.moveTo(bx + 7, rungY);
      ctx.lineTo(mix(bx + 7, bx + bw - 7, rungReveal), rungY);
      ctx.strokeStyle = rgba(SAGE, (0.12 + i * 0.025) * fade * rungReveal);
      ctx.lineWidth = 1;
      ctx.stroke();
    }
    ctx.restore();
  }

  function drawFamily(ctx, amount, fade) {
    // The complete family remains as an exceptionally faint scaffold so the
    // direction of growth is visible before the reveal begins.
    for (var i = 0; i < ROUNDS.length; i += 1) {
      var round = ROUNDS[i];
      drawArc(ctx, round.lift, BRANCH_FRAME, SEED_END_FRAME, 0.035 * fade, 1, round.drift, SAGE);
    }

    for (var branch = 0; branch < ROUNDS.length; branch += 1) {
      var item = ROUNDS[branch];
      var branchAmount = progress(amount, branch * 0.12, 0.58);
      var endFrame = mix(BRANCH_FRAME, SEED_END_FRAME, branchAmount);
      drawArc(ctx, item.lift, BRANCH_FRAME, endFrame, (0.2 + branch * 0.022) * fade, 1.35, item.drift, SAGE, false);

      var bodyReveal = progress(branchAmount, 0.58, 0.42);
      drawBody(ctx, item.pose, item.lift, 0.32 * bodyReveal * fade, SAGE, item.drift);

      if (bodyReveal > 0.01) {
        var endpoint = pointAt(item.pose, item.lift, item.drift);
        ctx.save();
        ctx.beginPath();
        ctx.arc(endpoint.x, endpoint.y, 2.2, 0, Math.PI * 2);
        ctx.fillStyle = rgba(SAGE, 0.5 * bodyReveal * fade);
        ctx.fill();
        ctx.restore();
      }
    }
  }

  function drawScene(ctx, t) {
    ctx.clearRect(-20, -VIEW_H, VIEW_W + 40, VIEW_H * 3);

    var familyAmount = progress(t, FAMILY_START, FAMILY_DURATION);
    var endFade = 1 - progress(t, FAMILY_START + FAMILY_DURATION + HOLD, FADE);
    var seedAmount = progress(t, SEED_START, SEED_DURATION);
    var seedFrame = mix(0, SEED_END_FRAME, seedAmount);

    ctx.save();
    ctx.strokeStyle = rgba(INK, 0.16 * endFade);
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(150, GROUND_Y + 0.5);
    ctx.lineTo(VIEW_W - 34, GROUND_Y + 0.5);
    ctx.stroke();
    ctx.restore();

    drawObstacle(ctx, familyAmount, endFade);
    drawFamily(ctx, familyAmount, endFade);
    drawSeedNode(ctx, t / 1100, endFade * (0.45 + 0.55 * familyAmount));

    var seedExit = 1 - progress(t, FAMILY_START + 260, 760);
    var enter = progress(seedAmount, 0, 0.08);
    var alpha = enter * seedExit * endFade * 0.62;
    drawArc(ctx, 0, 1, seedFrame, 0.34 * alpha, 1.5, 0, INK);

    // Onion-skin bodies, spaced by how far the hip has travelled.
    var nowX = HIP[clamp(Math.round(seedFrame), 0, LAST_FRAME)][0];
    var ghostFrame = seedFrame;
    for (var ghost = 1; ghost <= 2; ghost += 1) {
      var lag = ghost * 58;
      while (ghostFrame > 0 && nowX - HIP[clamp(Math.round(ghostFrame), 0, LAST_FRAME)][0] < lag) ghostFrame -= 0.5;
      if (ghostFrame <= 0) break;
      var ghostAlpha = alpha * (0.13 - ghost * 0.035);
      drawBody(ctx, ghostFrame, 0, ghostAlpha, SAGE, 0);
    }

    drawBody(ctx, seedFrame, 0, alpha, INK, 0);

    var contactAmount = progress(seedAmount, 0.58, 0.2) * (1 - progress(seedAmount, 0.9, 0.1));
    if (contactAmount > 0.01) {
      var contactPoint = pointAt(APEX, 0, 0);
      ctx.save();
      ctx.beginPath();
      ctx.arc(contactPoint.x, contactPoint.y, 3 + 10 * contactAmount, 0, Math.PI * 2);
      ctx.strokeStyle = rgba(CONTACT, 0.34 * contactAmount * endFade);
      ctx.lineWidth = 1;
      ctx.stroke();
      ctx.restore();
    }
  }

  // --------------------------------------------------------------- mounting

  var instances = new WeakMap();

  function mount(canvas) {
    if (!canvas || canvas.nodeName !== "CANVAS") return null;
    if (instances.has(canvas)) return instances.get(canvas);
    var context = canvas.getContext("2d", { alpha: true });
    if (!context) return null;

    var field = canvas.closest(".hero-tree-field");
    var header = canvas.closest(".article-header");
    var titleStage = header && header.querySelector(".hero-title-stage");

    var mediaQuery = typeof window.matchMedia === "function"
      ? window.matchMedia("(prefers-reduced-motion: reduce)")
      : null;
    var reduced = !!(mediaQuery && mediaQuery.matches);
    var STILL_T = FAMILY_START + FAMILY_DURATION + 900;
    var lastT = reduced ? STILL_T : 430;
    var frameId = 0;
    var startedAt = null;
    var visible = true;
    var destroyed = false;
    var resizeObserver = null;
    var intersection = null;

    // Keep the scene's ground line locked to the bottom edge of the headline.
    // A fixed top offset works at one viewport only: once the title gains or
    // loses a line, the runner floats above it. Measuring the rendered title
    // makes the composition follow the typography at every desktop width.
    function alignToTitle() {
      if (!field || !header || !titleStage || window.innerWidth <= 900) return;
      var fieldHeight = field.getBoundingClientRect().height;
      if (!fieldHeight) return;
      var groundCss = clamp(fieldHeight * 0.71, 240, fieldHeight - 190);
      var headerRect = header.getBoundingClientRect();
      var titleRect = titleStage.getBoundingClientRect();
      var nextTop = Math.max(0, titleRect.bottom - headerRect.top - groundCss);
      field.style.top = Math.round(nextTop) + "px";
    }

    function render(t) {
      lastT = t;
      drawScene(context, t);
    }

    function resize() {
      if (destroyed) return false;
      alignToTitle();
      var bounds = canvas.getBoundingClientRect();
      var width = Math.max(0, bounds.width);
      var height = Math.max(0, bounds.height);
      if (!width || !height) return false;
      var requestedDpr = clamp(window.devicePixelRatio || 1, 1, MAX_DPR);
      var budgetDpr = Math.sqrt(MAX_PIXEL_AREA / Math.max(1, width * height));
      var dpr = clamp(Math.min(requestedDpr, budgetDpr), 1, MAX_DPR);
      canvas.width = Math.max(1, Math.round(width * dpr));
      canvas.height = Math.max(1, Math.round(height * dpr));
      var scale = width / VIEW_W;
      var groundCss = clamp(height * 0.71, 240, height - 190);
      var offsetY = groundCss - GROUND_Y * scale;
      context.setTransform(dpr * scale, 0, 0, dpr * scale, 0, dpr * offsetY);
      render(lastT);
      return true;
    }

    function tick(now) {
      frameId = 0;
      if (destroyed || reduced || !visible || document.hidden) return;
      if (startedAt === null) startedAt = now - 430;
      var t = (now - startedAt) % CYCLE;
      render(t < 380 ? 380 : t);
      frameId = window.requestAnimationFrame(tick);
    }

    function play() {
      if (destroyed || reduced || frameId) return;
      frameId = window.requestAnimationFrame(tick);
    }

    function pause() {
      if (frameId) window.cancelAnimationFrame(frameId);
      frameId = 0;
    }

    function handleMotionChange(event) {
      reduced = event.matches;
      if (reduced) {
        pause();
        render(STILL_T);
      } else {
        startedAt = null;
        play();
      }
    }

    function handleVisibility() {
      if (document.hidden) pause();
      else play();
    }

    function destroy() {
      if (destroyed) return;
      destroyed = true;
      pause();
      if (resizeObserver) resizeObserver.disconnect();
      else window.removeEventListener("resize", resize);
      if (intersection) intersection.disconnect();
      document.removeEventListener("visibilitychange", handleVisibility);
      if (mediaQuery) {
        if (typeof mediaQuery.removeEventListener === "function") mediaQuery.removeEventListener("change", handleMotionChange);
        else if (typeof mediaQuery.removeListener === "function") mediaQuery.removeListener(handleMotionChange);
      }
      instances.delete(canvas);
    }

    var controller = {
      canvas: canvas,
      destroy: destroy,
      redraw: function () {
        if (!destroyed) resize();
      }
    };
    instances.set(canvas, controller);

    if (typeof ResizeObserver === "function") {
      resizeObserver = new ResizeObserver(resize);
      resizeObserver.observe(canvas);
      if (titleStage) resizeObserver.observe(titleStage);
    } else {
      window.addEventListener("resize", resize, { passive: true });
    }
    if (typeof IntersectionObserver === "function") {
      intersection = new IntersectionObserver(function (entries) {
        visible = entries[0] ? entries[0].isIntersecting : true;
        if (visible) play();
        else pause();
      }, { threshold: 0.05 });
      intersection.observe(canvas);
    }
    document.addEventListener("visibilitychange", handleVisibility);
    if (mediaQuery) {
      if (typeof mediaQuery.addEventListener === "function") mediaQuery.addEventListener("change", handleMotionChange);
      else if (typeof mediaQuery.addListener === "function") mediaQuery.addListener(handleMotionChange);
    }

    resize();
    if (reduced) render(STILL_T);
    else play();
    return controller;
  }

  function mountAll(root) {
    var scope = root || document;
    var canvases = [];
    if (scope.nodeName === "CANVAS" && scope.matches("canvas[data-hero-tree]")) canvases.push(scope);
    if (typeof scope.querySelectorAll === "function") {
      Array.prototype.push.apply(canvases, scope.querySelectorAll("canvas[data-hero-tree]"));
    }
    return canvases.map(mount).filter(Boolean);
  }

  window.LightParkourHeroTree = { mount: mount, mountAll: mountAll, version: VERSION };

  function autoMount() {
    mountAll(document);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", autoMount, { once: true });
  } else if (typeof window.queueMicrotask === "function") {
    window.queueMicrotask(autoMount);
  } else {
    window.setTimeout(autoMount, 0);
  }
})();
